EVENT_CONNECT = 'connect'
EVENT_DISCONNECT = 'disconnect'
EVENT_DISEASE_PREDICTION = 'disease_prediction'
EVENT_MESSAGE = 'message'
EVENT_RECEIVE_SYMPTOMS = 'receive_symptoms'
EVENT_ASK_FOR_CONTINUE_PREDICT = 'ask_for_continue_predict'
